-- Seed script for 32 Canadian Indigenous Grants
-- Run this in Supabase SQL Editor to populate the grants table

INSERT INTO grants (title, description, agency, program, category, eligibility, application_link, deadline, amount, currency, status, source_url, province, is_publicly_available, added_by, notes) VALUES

-- Federal Grants (16)
('Zero Emission Vehicle Infrastructure Program (ZEVIP)', 'Provides funding for EV charger deployment in public places, workplaces, multi-unit residential buildings, and fleets. Indigenous organizations receive enhanced funding at 75% vs 50% for non-Indigenous applicants.', 'Natural Resources Canada (NRCan)', 'ZEVIP', 'Electric Vehicles', 'Indigenous organizations, communities, First Nations (bands/councils), Tribal councils, Inuit organizations, Indigenous-owned businesses', 'https://natural-resources.canada.ca/energy-efficiency/transportation-energy-efficiency/zero-emission-vehicle-infrastructure-program', '2025-12-31', 'Up to 75% of project costs (max $2M for Indigenous organizations); $22,500-$150,000 per charger depending on output', 'CAD', 'inactive', 'https://natural-resources.canada.ca/energy-efficiency/transportation-energy-efficiency/zero-emission-vehicle-infrastructure-program', 'Federal', true, 'seed-script', 'Original deadline info: Indigenous stream currently closed; General stream open until funding committed'),

('Canada Infrastructure Bank Indigenous Community Infrastructure Initiative (ICII)', 'Low-cost, long-term financing for revenue-generating infrastructure projects across 5 priority sectors: clean power, green infrastructure, public transit, broadband, trade and transportation.', 'Canada Infrastructure Bank (CIB)', 'ICII', 'Infrastructure', 'First Nation, Métis and Inuit communities and their economic development corporations', 'https://cib-bic.ca/en/indigenous-community-infrastructure/', '2025-12-31', 'Low-interest loans minimum $5M, up to 80% of project costs; $1B+ committed to Indigenous projects', 'CAD', 'active', 'https://cib-bic.ca/en/indigenous-infra/', 'Federal', true, 'seed-script', 'Original deadline info: Ongoing'),

('Canada Infrastructure Bank Indigenous Equity Initiative (IEI)', 'Provides loans to Indigenous communities to support them in purchasing equity ownership stakes in infrastructure projects within their traditional territories.', 'Canada Infrastructure Bank (CIB)', 'IEI', 'Economic Development', 'First Nation, Métis and Inuit communities seeking equity stakes in infrastructure projects', 'https://cib-bic.ca/en/indigenous-equity-initiative/', '2025-12-31', 'Loans for equity purchases in projects where CIB is also investing', 'CAD', 'active', 'https://cib-bic.ca/en/medias/articles/canada-infrastructure-bank-launches-new-indigenous-equity-initiative/', 'Federal', true, 'seed-script', 'Original deadline info: Ongoing'),

('Wah-ila-toos / Clean Energy for Rural and Remote Communities (CERRC)', 'Supports clean energy projects (wind, solar, hydro, biomass, geothermal) to reduce diesel reliance in Indigenous, rural and remote communities. Single-window approach through Wah-ila-toos hub.', 'Natural Resources Canada (NRCan)', 'CERRC', 'Environment', 'First Nations, Inuit, Métis communities, Indigenous governments, tribal councils, development corporations, Indigenous organizations', 'https://natural-resources.canada.ca/funding-partnerships/clean-energy-rural-remote-communities-program', '2025-12-31', 'Up to $5M per project; $453M program over 8 years', 'CAD', 'active', 'https://natural-resources.canada.ca/funding-partnerships/clean-energy-rural-remote-communities-program', 'Federal', true, 'seed-script', 'Original deadline info: Ongoing (some streams on waitlist due to limited funding)'),

('Northern REACHE Program', 'Supports northern and Indigenous communities in transitioning to renewable, sustainable and affordable energy sources. Part of Wah-ila-toos initiative.', 'Crown-Indigenous Relations and Northern Affairs Canada (CIRNAC)', 'Northern REACHE', 'Environment', 'Northern and Indigenous communities transitioning to renewable energy', 'https://www.rcaanc-cirnac.gc.ca/eng/1481305379258/1594737453888', '2025-12-31', '$300M over 5 years; $40.4M for hydroelectricity feasibility/planning', 'CAD', 'active', 'https://www.rcaanc-cirnac.gc.ca/eng/1481305379258/1594737453888', 'Federal', true, 'seed-script', 'Original deadline info: Ongoing'),

('Indigenous Leadership Fund (Low Carbon Economy Fund)', 'Funds Indigenous-owned and led renewable energy, energy efficiency, and low-carbon heating projects. Projects must be past concept stage and ready for deployment.', 'Environment and Climate Change Canada (ECCC)', 'Indigenous Leadership Fund', 'Environment', 'First Nations, Inuit, Métis governments, communities, organizations (must be 51%+ Indigenous-owned)', 'https://www.canada.ca/en/environment-climate-change/services/climate-change/low-carbon-economy-fund/indigenous-leadership.html', '2025-12-31', 'Up to $180M by 2029; First Nations stream up to $6M/project; Designated stream up to $1M/project', 'CAD', 'inactive', 'https://www.canada.ca/en/environment-climate-change/services/climate-change/low-carbon-economy-fund/indigenous-leadership.html', 'Federal', true, 'seed-script', 'Original deadline info: First Nations and Designated streams currently closed; Métis stream remains open'),

('Smart Renewables and Electrification Pathways Program - Indigenous-Led Clean Energy Stream', 'Supports Indigenous-led clean electricity deployment (wind, solar, hydro, battery storage) and grid modernization projects with direct community benefits.', 'Natural Resources Canada (NRCan)', 'SREPs ILCE', 'Environment', 'Indigenous-led projects demonstrating meaningful Indigenous ownership/participation', 'https://natural-resources.canada.ca/climate-change/indigenous-clean-energy-stream', '2025-12-31', '$4.5B total program; variable per project based on scope', 'CAD', 'inactive', 'https://natural-resources.canada.ca/climate-change/indigenous-clean-energy-stream', 'Federal', true, 'seed-script', 'Original deadline info: Spring 2025 RFP closed; future intakes expected'),

('First Nation Adapt Program', 'Supports climate change adaptation projects including risk assessments, flood mapping, small-scale implementation of adaptation actions for flooding, wildfires, drought, sea level rise.', 'Crown-Indigenous Relations and Northern Affairs Canada (CIRNAC)', 'First Nation Adapt', 'Environment', 'First Nation communities and organizations south of 60th parallel', 'https://www.rcaanc-cirnac.gc.ca/eng/1520877017867/1594751383101', '2025-12-31', 'Variable; dedicated flood mapping and water resiliency funding available through 2025-26', 'CAD', 'active', 'https://www.rcaanc-cirnac.gc.ca/eng/1520877017867/1594751383101', 'Federal', true, 'seed-script', 'Original deadline info: Ongoing intake'),

('Indigenous-led Natural Climate Solutions', 'Supports ecological restoration, improved land management, and conservation activities that sequester carbon while benefiting biodiversity, climate resiliency, and human well-being.', 'Environment and Climate Change Canada (ECCC)', 'ILNCS (Nature Smart Climate Solutions Fund)', 'Environment', 'First Nations, Inuit, Métis Nations, communities and organizations', 'https://www.canada.ca/en/environment-climate-change/services/environmental-funding/programs/indigenous-led-natural-climate-solutions.html', '2025-12-31', 'Up to $76.9M over 10 years for Indigenous stream', 'CAD', 'active', 'https://www.canada.ca/en/environment-climate-change/services/environmental-funding/programs/indigenous-led-natural-climate-solutions.html', 'Federal', true, 'seed-script', 'Original deadline info: Ongoing through Indigenous Guardians Secretariat'),

('Community Opportunity Readiness Program (CORP)', 'Provides funding for economic opportunities, business planning, advisory services, commercial development, and equity gap financing for community-owned businesses.', 'Indigenous Services Canada (ISC)', 'CORP', 'Economic Development', 'First Nation and Inuit communities and their governments, tribal councils', 'https://www.sac-isc.gc.ca/eng/1100100033417/1613659339457', '2026-03-31', 'Up to $250K (Regional Process); larger projects through National Prioritization Framework; 30-80% of project costs', 'CAD', 'active', 'https://www.sac-isc.gc.ca/eng/1100100033417/1613659339457', 'Federal', true, 'seed-script', 'Original deadline info: 2025-26 intake reopened November 1, 2025, runs until March 31, 2026'),

('Strategic Partnerships Initiative (SPI)', 'Horizontal program coordinating federal investments in Indigenous economic development across multiple departments. Additional funding for clean energy initiatives.', 'Indigenous Services Canada (ISC)', 'SPI', 'Economic Development', 'Indigenous businesses, organizations, communities, local governments (through federal partner referral)', 'https://www.sac-isc.gc.ca/eng/1330016561558/1594122175203', '2025-12-31', '$14.45M annual budget + $12M annually for clean energy until 2027', 'CAD', 'active', 'https://www.sac-isc.gc.ca/eng/1330016561558/1594122175203', 'Federal', true, 'seed-script', 'Original deadline info: Ongoing (recipients cannot apply directly; identified through federal partners)'),

('Aboriginal Entrepreneurship Program - Access to Capital', 'Promotes Indigenous entrepreneurship by providing access to capital and business services through network of Indigenous Financial Institutions to start, expand or acquire businesses.', 'Indigenous Services Canada (ISC) / NACCA Network', 'AEP', 'Economic Development', 'Indigenous entrepreneurs through Indigenous Financial Institutions (IFIs) and Métis Capital Corporations', 'https://www.sac-isc.gc.ca/eng/1375201178602/1610797286236', '2025-12-31', '$514M over 10 years (2024-2034); non-repayable equity contributions for businesses', 'CAD', 'active', 'https://www.sac-isc.gc.ca/eng/1375201178602/1610797286236', 'Federal', true, 'seed-script', 'Original deadline info: Ongoing through IFI network'),

('First Nation Infrastructure Fund (FNIF)', 'Supports planning and skills development, solid waste management, roads and bridges, energy systems, connectivity, fire protection, cultural/recreational facilities, band administrative buildings.', 'Indigenous Services Canada (ISC)', 'FNIF', 'Infrastructure', 'First Nations governments, Indigenous-owned entities, partners working with Indigenous communities', 'https://www.sac-isc.gc.ca/eng/1100100010656/1533645154710', '2025-12-31', 'Up to $10M per recipient per year for capital projects', 'CAD', 'active', 'https://www.sac-isc.gc.ca/eng/1100100010656/1533645154710', 'Federal', true, 'seed-script', 'Original deadline info: FNIIP submission deadline in fall each year; no deadline for funding'),

('Green and Inclusive Community Buildings Program (GICB)', 'Supports green retrofits and new construction of community buildings to reduce GHG emissions and improve accessibility. Indigenous and territorial projects receive enhanced funding.', 'Housing, Infrastructure and Communities Canada', 'GICB', 'Infrastructure', 'Indigenous governing bodies, band councils, Indigenous not-for-profits, Indigenous development corporations', 'https://housing-infrastructure.canada.ca/gicb-bcvi/index-eng.html', '2029-03-31', 'Up to $25M; Indigenous projects can receive up to 100% funding; At least 10% of program funding for Indigenous recipients', 'CAD', 'active', 'https://housing-infrastructure.canada.ca/gicb-bcvi/index-eng.html', 'Federal', true, 'seed-script', 'Original deadline info: Extended to March 2029; periodic intakes'),

('Disaster Mitigation and Adaptation Fund (DMAF)', 'Invests in structural and natural infrastructure to increase community resilience against natural disasters triggered by climate change.', 'Housing, Infrastructure and Communities Canada', 'DMAF', 'Infrastructure', 'Indigenous governing bodies, band councils, Indigenous development corporations, not-for-profits with Indigenous mandate', 'https://housing-infrastructure.canada.ca/dmaf-faac/index-eng.html', '2025-12-31', '$1B+ available; minimum $138M allocated to Indigenous recipients', 'CAD', 'active', 'https://housing-infrastructure.canada.ca/dmaf-faac/index-eng.html', 'Federal', true, 'seed-script', 'Original deadline info: Currently accepting applications'),

('Indigenous Skills and Employment Training (ISET) Program', 'Helps Indigenous people improve skills and find employment through distinctions-based approach for First Nations, Métis and Inuit.', 'Employment and Social Development Canada (ESDC)', 'ISET', 'Economic Development', 'Indigenous people seeking skills training and employment through Indigenous service delivery organizations', 'https://www.canada.ca/en/employment-social-development/programs/indigenous-skills-employment-training.html', '2025-12-31', 'Variable; funding for tuition, books, training supports, living expenses', 'CAD', 'active', 'https://www.canada.ca/en/employment-social-development/programs/indigenous-skills-employment-training.html', 'Federal', true, 'seed-script', 'Original deadline info: Ongoing through Indigenous service delivery organizations'),

-- Ontario Grants (4)
('EV ChargeON Program', 'Provides funding for public EV charger installation. Indigenous communities and Northern Ontario projects receive enhanced 75% funding rate.', 'Ontario Ministry of Transportation / OVIN', 'EV ChargeON', 'Electric Vehicles', 'Indigenous communities, Indigenous-owned businesses (majority ownership), municipalities, broader public sector', 'https://www.ovinhub.ca/programs/evchargeon/', '2025-12-15', 'Up to $1M per project; Indigenous communities eligible for up to 75% of project costs', 'CAD', 'active', 'https://www.ovinhub.ca/programs/evchargeon/', 'Ontario', true, 'seed-script', 'Original deadline info: December 15, 2025 (current intake)'),

('Indigenous Energy Support Program (IESP)', 'Supports capacity building, community energy planning, clean energy project development, feasibility studies, and energy resiliency initiatives.', 'Independent Electricity System Operator (IESO)', 'IESP', 'Environment', 'First Nation and Métis communities and organizations in Ontario', 'https://www.ieso.ca/Get-Involved/Indigenous-Relations/Indigenous-Energy-Support-Program/IESP-Overview', '2025-10-03', '$25M provincial funding; $500K/year per remote First Nation for diesel reduction', 'CAD', 'inactive', 'https://www.ieso.ca/Get-Involved/Indigenous-Relations/Indigenous-Energy-Support-Program/IESP-Overview', 'Ontario', true, 'seed-script', 'Original deadline info: August 26 - October 3, 2025 (annual intake)'),

('Indigenous Economic Development Fund (IEDF)', 'Supports economic diversification, business start-up/expansion, employment and training, regional partnerships for Indigenous economic development.', 'Ontario Ministry of Indigenous Affairs', 'IEDF', 'Economic Development', 'Indigenous entrepreneurs, businesses, First Nation and Métis communities, Indigenous organizations', 'http://www.ontario.ca/page/funding-indigenous-economic-development', '2025-12-01', '$70M over 7 years; grants through Economic Diversification Grant, Business and Community Fund, Regional Partnership Grant', 'CAD', 'active', 'http://www.ontario.ca/page/funding-indigenous-economic-development', 'Ontario', true, 'seed-script', 'Original deadline info: December 1, 2025 (current intake)'),

('Indigenous Opportunities Financing Program (IOFP)', 'Provides government-backed financing for First Nations equity ownership in new transmission or renewable energy projects (wind, solar, hydroelectric).', 'Ontario Ministry of Energy', 'IOFP', 'Environment', 'First Nations for equity ownership in energy projects (transmission, renewable energy)', 'Contact Ontario Ministry of Energy', '2025-12-31', 'Government-backed financing; $1.34M minimum loan guarantee', 'CAD', 'active', 'https://www.pembina.org/reports/restoring-the-flow-pembina-institute-10.-ontario.pdf', 'Ontario', true, 'seed-script', 'Original deadline info: Ongoing'),

-- British Columbia Grants (3)
('First Nations Clean Energy Business Fund (FNCEBF)', 'Supports clean energy feasibility studies, community energy planning, equity positions in clean energy projects, and revenue sharing from clean energy projects.', 'BC Ministry of Energy and Climate Solutions', 'FNCEBF', 'Environment', 'BC First Nations (bands under Indian Act or governing bodies representing one or more First Nations)', 'https://www2.gov.bc.ca/gov/content/environment/natural-resource-stewardship/consulting-with-first-nations/first-nations-clean-energy-business-fund', '2026-01-31', 'Capacity: up to $50K; Equity: up to $500K per applicant ($150K per project); plus revenue sharing agreements', 'CAD', 'inactive', 'https://www2.gov.bc.ca/gov/content/environment/natural-resource-stewardship/consulting-with-first-nations/first-nations-clean-energy-business-fund', 'British Columbia', true, 'seed-script', 'Original deadline info: Next intake early 2026; April 30, 2025 deadline passed'),

('BC Indigenous Clean Energy Initiative (BCICEI)', 'Provides support and capacity-building funds for Indigenous clean energy projects including pre-construction, feasibility, engineering, and deployment.', 'New Relationship Trust / Pacific Economic Development Canada', 'BCICEI', 'Environment', 'First Nations throughout BC for clean energy projects', 'https://newrelationshiptrust.ca/indigenous-clean-energy-initiative-bcicei/', '2025-12-31', '$9.8M (federal/provincial combined) in 2024; project-specific amounts vary', 'CAD', 'active', 'https://newrelationshiptrust.ca/indigenous-clean-energy-initiative-bcicei/', 'British Columbia', true, 'seed-script', 'Original deadline info: Ongoing through New Relationship Trust'),

('Indigenous Communities Conservation Program (ICCP)', 'Provides free energy-saving products, training stipends, and rebates for home energy efficiency upgrades including insulation, windows, heating systems.', 'BC Hydro / FortisBC', 'ICCP', 'Environment', 'Indigenous communities and Indigenous housing providers in BC Hydro/FortisBC service territory', 'https://www.betterhomesbc.ca/rebates/indigenous-communities-conservation-program/', '2025-12-31', 'Free energy-saving products, salary funding for training, rebates for home energy upgrades', 'CAD', 'active', 'https://www.betterhomesbc.ca/rebates/indigenous-communities-conservation-program/', 'British Columbia', true, 'seed-script', 'Original deadline info: No deadline'),

-- Alberta Grants (4)
('Alberta Indigenous Opportunities Corporation (AIOC)', 'Provides loan guarantees to increase access to capital and improve lending terms for Indigenous investments in major projects across multiple sectors.', 'Alberta Indigenous Opportunities Corporation', 'AIOC', 'Economic Development', 'Indigenous communities for investments in natural resources, agriculture, telecommunications, transportation, tourism, healthcare, technology', 'https://theaioc.com', '2025-12-31', '$3B loan guarantee program; minimum $20M Indigenous investment per project; max $250M guarantee per investment', 'CAD', 'active', 'https://theaioc.com', 'Alberta', true, 'seed-script', 'Original deadline info: Ongoing'),

('Alberta Indigenous Clean Energy Initiative (AICEI)', 'Supports renewable energy generation, energy efficiency improvements, capacity building, community energy planning, feasibility studies for Indigenous communities.', 'Prairies Economic Development Canada (PrairiesCan)', 'AICEI', 'Environment', 'First Nations, Métis Settlements, Métis and non-status Indigenous communities, Indigenous-owned businesses in Alberta', 'https://www.canada.ca/en/prairies-economic-development/services/funding/alberta-indigenous-clean-energy-initiative.html', '2025-12-31', 'Variable; supports capacity building to project completion', 'CAD', 'active', 'https://www.canada.ca/en/prairies-economic-development/services/funding/alberta-indigenous-clean-energy-initiative.html', 'Alberta', true, 'seed-script', 'Original deadline info: Ongoing (conversation-based, no formal application)'),

('Aboriginal Business Investment Fund (ABIF)', 'Helps Indigenous community-owned businesses capitalize on business development opportunities to improve socio-economic outcomes.', 'Alberta Indigenous Relations', 'ABIF', 'Economic Development', 'Indigenous communities or corporate entities 51%+ owned by Indigenous communities in Alberta', 'https://www.alberta.ca/indigenous-funding-resources', '2025-12-31', '$150,000 to $750,000 per project', 'CAD', 'active', 'https://www.alberta.ca/indigenous-funding-resources', 'Alberta', true, 'seed-script', 'Original deadline info: One application per community per funding year'),

('Northern and Regional Economic Development Program (NRED)', 'Supports economic development and diversification projects including feasibility studies, business plans, tourism development, small business incubators.', 'Alberta Agriculture and Irrigation', 'NRED', 'Economic Development', 'Indigenous communities in Alberta; up to 75% for Indigenous applicants', 'https://www.alberta.ca/northern-and-regional-economic-development-program', '2025-12-31', 'Up to 75% of eligible costs (min $13,333 project); grants range $25K-$300K', 'CAD', 'active', 'https://www.alberta.ca/northern-and-regional-economic-development-program', 'Alberta', true, 'seed-script', 'Original deadline info: Annual intakes'),

-- Quebec Grants (1)
('Indigenous Initiatives Fund IV (IIF IV)', 'Seven-component program supporting economic development, community infrastructure, loan guarantees, community action, social development, consultation support, and urban Indigenous services.', 'Secrétariat aux affaires autochtones (Quebec)', 'IIF IV', 'Economic Development', 'Indigenous communities, businesses, entrepreneurs, organizations in Quebec', 'https://www.quebec.ca/en/gouvernement/portrait-quebec/premieres-nations-inuits/aides-financieres-autochtones/fond-initiatives-autochtones', '2027-12-31', 'Variable by component (Economic Development, Community Infrastructure, Loan Guarantees, Social Development, etc.)', 'CAD', 'active', 'https://www.quebec.ca/en/gouvernement/portrait-quebec/premieres-nations-inuits/aides-financieres-autochtones/fond-initiatives-autochtones', 'Quebec', true, 'seed-script', 'Original deadline info: 2022-2027 program period'),

-- Manitoba Grants (2)
('Indigenous Economic Development Fund (Manitoba)', 'Supports Indigenous economic reconciliation and inclusion through grants for Indigenous business owners and entrepreneurs.', 'Manitoba Indigenous Economic Development', 'IEDF Manitoba', 'Economic Development', 'Indigenous business owners and entrepreneurs in Manitoba', 'https://www.gov.mb.ca/ied/index.html', '2025-12-31', '$4M initial investment; grants for programs and services', 'CAD', 'active', 'https://www.gov.mb.ca/ied/index.html', 'Manitoba', true, 'seed-script', 'Original deadline info: Ongoing'),

('First Peoples Economic Growth Fund', 'Provides financial support to First Nations businesses for startup, expansion, and acquisition.', 'Community Futures Manitoba', 'FPEGF', 'Economic Development', 'First Nations businesses in Manitoba', 'https://cfmanitoba.ca/loans-and-advice/tools-resources/indigenous-business-services', '2025-12-31', 'Variable; financial support for business development', 'CAD', 'active', 'https://cfmanitoba.ca/loans-and-advice/tools-resources/indigenous-business-services', 'Manitoba', true, 'seed-script', 'Original deadline info: Ongoing'),

-- Saskatchewan Grants (2)
('Saskatchewan Indigenous Enterprise Foundation (SIEF)', 'Needs-based conditional grant program for First Nation entrepreneurs and businesses. Includes dedicated Indigenous Women Entrepreneur program.', 'Saskatchewan Indigenous Enterprise Foundation', 'SIEF Contribution Program', 'Economic Development', 'First Nation entrepreneurs and businesses in Saskatchewan', 'https://sief.sk.ca', '2025-12-31', 'Conditional grants; Indigenous Women Entrepreneur (IWE) program available', 'CAD', 'active', 'https://sief.sk.ca', 'Saskatchewan', true, 'seed-script', 'Original deadline info: Ongoing'),

('First Nations and Métis Community Partnership Projects', 'Supports innovative partnership projects in safe communities, strong families, student achievement, and economic growth categories.', 'Saskatchewan Ministry of Government Relations', 'FNMCPP', 'Economic Development', 'First Nations Band/Tribal Councils, Métis Nation, Aboriginal non-profits, municipalities partnering with Indigenous communities', 'https://www.saskatchewan.ca/government/news-and-media/2025/october/21/grant-programs-open-to-support-indigenous-community-safety', '2025-10-31', 'Up to $45,000 per project', 'CAD', 'active', 'http://skfn.ca/business-economic-development-programs/', 'Saskatchewan', true, 'seed-script', 'Original deadline info: October 31 annually');
