// Mock grant data for demonstration
export const mockGrants = [
  {
    id: '1',
    title: 'Indigenous Clean Energy Initiative',
    description: 'Funding for renewable energy projects in Indigenous communities, including solar, wind, and hydro installations.',
    agency: 'Natural Resources Canada',
    program: 'Clean Energy for Rural and Remote Communities',
    category: 'Environment & Energy',
    eligibility: 'Indigenous, Inuit, and Métis communities in rural and remote areas',
    applicationLink: 'https://www.nrcan.gc.ca/cerrc',
    deadline: '2025-03-31',
    amount: '500000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.nrcan.gc.ca',
  },
  {
    id: '2',
    title: 'Indigenous Language Revitalization Grant',
    description: 'Support for projects that preserve, promote, and revitalize Indigenous languages through education and community programs.',
    agency: 'Canadian Heritage',
    program: 'Indigenous Languages and Cultures Program',
    category: 'Culture & Education',
    eligibility: 'Indigenous organizations, communities, and educational institutions',
    applicationLink: 'https://www.canada.ca/indigenous-languages',
    deadline: '2025-05-15',
    amount: '250000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.canada.ca',
  },
  {
    id: '3',
    title: 'Indigenous Business Development Fund',
    description: 'Financial assistance for Indigenous entrepreneurs to start or expand businesses, including training and mentorship support.',
    agency: 'Indigenous Services Canada',
    program: 'Aboriginal Business Development Program',
    category: 'Economic Development',
    eligibility: 'Indigenous-owned businesses and entrepreneurs',
    applicationLink: 'https://www.sac-isc.gc.ca/business',
    deadline: '2025-06-30',
    amount: '150000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.sac-isc.gc.ca',
  },
  {
    id: '4',
    title: 'Community Infrastructure Enhancement',
    description: 'Funding for infrastructure projects including water systems, housing, roads, and community facilities in Indigenous communities.',
    agency: 'Infrastructure Canada',
    program: 'Investing in Canada Infrastructure Program',
    category: 'Infrastructure',
    eligibility: 'Indigenous, Inuit, and Métis governments and organizations',
    applicationLink: 'https://www.infrastructure.gc.ca/indigenous',
    deadline: '2025-08-31',
    amount: '2000000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.infrastructure.gc.ca',
  },
  {
    id: '5',
    title: 'Youth Education and Skills Development',
    description: 'Programs supporting Indigenous youth in education, skills training, and employment opportunities.',
    agency: 'Employment and Social Development Canada',
    program: 'Indigenous Skills and Employment Training',
    category: 'Education & Employment',
    eligibility: 'Indigenous youth aged 15-30',
    applicationLink: 'https://www.canada.ca/iset',
    deadline: '2025-04-30',
    amount: '300000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.canada.ca',
  },
  {
    id: '6',
    title: 'Traditional Arts and Crafts Support',
    description: 'Grants for Indigenous artists and craftspeople to preserve traditional art forms and develop commercial opportunities.',
    agency: 'Canada Council for the Arts',
    program: 'Indigenous Arts Program',
    category: 'Arts & Culture',
    eligibility: 'Indigenous artists, artisans, and cultural organizations',
    applicationLink: 'https://canadacouncil.ca/indigenous',
    deadline: '2025-07-15',
    amount: '75000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://canadacouncil.ca',
  },
  {
    id: '7',
    title: 'Indigenous Health and Wellness Initiative',
    description: 'Support for community-based health programs, mental health services, and wellness activities in Indigenous communities.',
    agency: 'Health Canada',
    program: 'Indigenous and Inuit Health Branch',
    category: 'Health & Wellness',
    eligibility: 'Indigenous and Inuit health organizations',
    applicationLink: 'https://www.canada.ca/indigenous-health',
    deadline: '2025-09-30',
    amount: '400000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.canada.ca',
  },
  {
    id: '8',
    title: 'Environmental Stewardship and Conservation',
    description: 'Funding for Indigenous-led environmental protection, land management, and conservation projects.',
    agency: 'Environment and Climate Change Canada',
    program: 'Indigenous Guardians Program',
    category: 'Environment & Conservation',
    eligibility: 'Indigenous governments and organizations',
    applicationLink: 'https://www.canada.ca/guardians',
    deadline: '2025-05-31',
    amount: '600000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.canada.ca',
  },
  {
    id: '9',
    title: 'Housing and Shelter Development',
    description: 'Capital funding for new housing construction and renovation of existing housing in Indigenous communities.',
    agency: 'Canada Mortgage and Housing Corporation',
    program: 'Indigenous Housing Strategy',
    category: 'Housing',
    eligibility: 'Indigenous housing providers and communities',
    applicationLink: 'https://www.cmhc-schl.gc.ca/indigenous',
    deadline: '2025-10-31',
    amount: '1500000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.cmhc-schl.gc.ca',
  },
  {
    id: '10',
    title: 'Technology and Digital Innovation',
    description: 'Support for technology projects including broadband infrastructure, digital literacy, and tech entrepreneurship in Indigenous communities.',
    agency: 'Innovation, Science and Economic Development Canada',
    program: 'Connecting Families Initiative',
    category: 'Technology & Innovation',
    eligibility: 'Indigenous organizations and tech entrepreneurs',
    applicationLink: 'https://www.ic.gc.ca/indigenous-tech',
    deadline: '2025-06-15',
    amount: '350000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.ic.gc.ca',
  },
];

// Mock user applications data
export const mockApplications = [
  {
    id: 'app-1',
    grantId: '1',
    grantTitle: 'Indigenous Clean Energy Initiative',
    agency: 'Natural Resources Canada',
    applicationStatus: 'submitted',
    applicationDate: '2024-12-15',
    submissionDate: '2025-01-10',
    amountRequested: '500000',
    notes: 'Submitted proposal for solar panel installation in community center',
    deadline: '2025-03-31',
  },
  {
    id: 'app-2',
    grantId: '2',
    grantTitle: 'Indigenous Language Revitalization Grant',
    agency: 'Canadian Heritage',
    applicationStatus: 'approved',
    applicationDate: '2024-11-20',
    submissionDate: '2024-12-05',
    responseDate: '2025-01-15',
    amountRequested: '150000',
    amountApproved: '150000',
    notes: 'Approved for language education program. First installment received.',
    deadline: '2025-05-15',
  },
  {
    id: 'app-3',
    grantId: '5',
    grantTitle: 'Youth Education and Skills Development',
    agency: 'Employment and Social Development Canada',
    applicationStatus: 'in_progress',
    applicationDate: '2025-01-05',
    amountRequested: '200000',
    notes: 'Currently gathering required documentation and community support letters',
    deadline: '2025-04-30',
  },
  {
    id: 'app-4',
    grantId: '9',
    grantTitle: 'Housing and Shelter Development',
    agency: 'Canada Mortgage and Housing Corporation',
    applicationStatus: 'planning',
    applicationDate: '2025-01-18',
    amountRequested: '1200000',
    notes: 'Initial planning phase for 15-unit housing development',
    deadline: '2025-10-31',
  },
  {
    id: 'app-5',
    grantId: '7',
    grantTitle: 'Indigenous Health and Wellness Initiative',
    agency: 'Health Canada',
    applicationStatus: 'under_review',
    applicationDate: '2024-12-01',
    submissionDate: '2024-12-20',
    amountRequested: '300000',
    notes: 'Application under review by evaluation committee',
    deadline: '2025-09-30',
  },
];

// Mock metrics data
export const mockMetrics = {
  overview: {
    totalApplications: 5,
    approved: 1,
    pending: 3,
    rejected: 0,
    totalRequested: 2350000,
    totalApproved: 150000,
    successRate: 20,
  },
  byStatus: [
    { status: 'Approved', count: 1, percentage: 20, color: 'bg-green-500' },
    { status: 'Under Review', count: 1, percentage: 20, color: 'bg-yellow-500' },
    { status: 'Submitted', count: 1, percentage: 20, color: 'bg-blue-500' },
    { status: 'In Progress', count: 1, percentage: 20, color: 'bg-purple-500' },
    { status: 'Planning', count: 1, percentage: 20, color: 'bg-gray-500' },
  ],
  byCategory: [
    { category: 'Environment & Energy', applications: 1, approved: 0, amountRequested: 500000 },
    { category: 'Culture & Education', applications: 1, approved: 1, amountRequested: 150000 },
    { category: 'Education & Employment', applications: 1, approved: 0, amountRequested: 200000 },
    { category: 'Housing', applications: 1, approved: 0, amountRequested: 1200000 },
    { category: 'Health & Wellness', applications: 1, approved: 0, amountRequested: 300000 },
  ],
  timeline: [
    { month: 'Nov 2024', applications: 1, approvals: 0 },
    { month: 'Dec 2024', applications: 2, approvals: 0 },
    { month: 'Jan 2025', applications: 2, approvals: 1 },
  ],
};
