// Mock grant data for demonstration
export const mockGrants = [
  {
    id: '1',
    title: 'Indigenous Clean Energy Initiative',
    description: 'Funding for renewable energy projects in Indigenous communities, including solar, wind, and hydro installations.',
    agency: 'Natural Resources Canada',
    program: 'Clean Energy for Rural and Remote Communities',
    category: 'Environment',
    eligibility: 'Indigenous, Inuit, and Métis communities in rural and remote areas',
    applicationLink: 'https://www.nrcan.gc.ca/cerrc',
    deadline: '2025-03-31',
    amount: '500000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.nrcan.gc.ca',
  },
  {
    id: '2',
    title: 'Indigenous Electric Vehicle Fleet Program',
    description: 'Funding to support the purchase of electric vehicles and charging infrastructure for Indigenous communities and businesses.',
    agency: 'Transport Canada',
    program: 'Zero-Emission Vehicle Infrastructure Program',
    category: 'Electric Vehicles',
    eligibility: 'Indigenous communities, bands, and Indigenous-owned businesses',
    applicationLink: 'https://www.tc.gc.ca/zevip',
    deadline: '2025-05-15',
    amount: '250000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.tc.gc.ca',
  },
  {
    id: '3',
    title: 'Indigenous Business Development Fund',
    description: 'Financial assistance for Indigenous entrepreneurs to start or expand businesses, including training and mentorship support.',
    agency: 'Indigenous Services Canada',
    program: 'Aboriginal Business Development Program',
    category: 'Economic Development',
    eligibility: 'Indigenous-owned businesses and entrepreneurs',
    applicationLink: 'https://www.sac-isc.gc.ca/business',
    deadline: '2025-06-30',
    amount: '150000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.sac-isc.gc.ca',
  },
  {
    id: '4',
    title: 'Community Infrastructure Enhancement',
    description: 'Funding for infrastructure projects including water systems, housing, roads, and community facilities in Indigenous communities.',
    agency: 'Infrastructure Canada',
    program: 'Investing in Canada Infrastructure Program',
    category: 'Infrastructure',
    eligibility: 'Indigenous, Inuit, and Métis governments and organizations',
    applicationLink: 'https://www.infrastructure.gc.ca/indigenous',
    deadline: '2025-08-31',
    amount: '2000000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.infrastructure.gc.ca',
  },
  {
    id: '5',
    title: 'EV Charging Station Infrastructure Grant',
    description: 'Support for installing electric vehicle charging stations in Indigenous communities to promote clean transportation.',
    agency: 'Natural Resources Canada',
    program: 'Zero-Emission Vehicle Infrastructure Program',
    category: 'Electric Vehicles',
    eligibility: 'Indigenous communities and organizations',
    applicationLink: 'https://www.nrcan.gc.ca/zevip',
    deadline: '2025-04-30',
    amount: '300000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.nrcan.gc.ca',
  },
  {
    id: '6',
    title: 'Indigenous Clean Transportation Initiative',
    description: 'Funding for transitioning community fleets to electric vehicles, including buses, utility vehicles, and service trucks.',
    agency: 'Environment and Climate Change Canada',
    program: 'Clean Transportation Program',
    category: 'Electric Vehicles',
    eligibility: 'Indigenous bands, communities, and tribal councils',
    applicationLink: 'https://www.ec.gc.ca/clean-transport',
    deadline: '2025-07-15',
    amount: '750000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.ec.gc.ca',
  },
  {
    id: '7',
    title: 'Green Energy Microgrid Development',
    description: 'Support for developing renewable energy microgrids integrated with EV charging infrastructure in remote Indigenous communities.',
    agency: 'Natural Resources Canada',
    program: 'Smart Renewables and Electrification Pathways',
    category: 'Environment',
    eligibility: 'Indigenous communities in remote and off-grid areas',
    applicationLink: 'https://www.nrcan.gc.ca/srep',
    deadline: '2025-09-30',
    amount: '1200000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.nrcan.gc.ca',
  },
  {
    id: '8',
    title: 'Environmental Stewardship and Conservation',
    description: 'Funding for Indigenous-led environmental protection, land management, and conservation projects.',
    agency: 'Environment and Climate Change Canada',
    program: 'Indigenous Guardians Program',
    category: 'Environment',
    eligibility: 'Indigenous governments and organizations',
    applicationLink: 'https://www.canada.ca/guardians',
    deadline: '2025-05-31',
    amount: '600000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.canada.ca',
  },
  {
    id: '9',
    title: 'Electric School Bus Program',
    description: 'Funding to replace diesel school buses with electric buses, including charging infrastructure for Indigenous schools and communities.',
    agency: 'Transport Canada',
    program: 'Zero-Emission Transit Fund',
    category: 'Electric Vehicles',
    eligibility: 'Indigenous school boards and education authorities',
    applicationLink: 'https://www.tc.gc.ca/zetf',
    deadline: '2025-10-31',
    amount: '850000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.tc.gc.ca',
  },
  {
    id: '10',
    title: 'Technology and Digital Innovation',
    description: 'Support for technology projects including broadband infrastructure, digital literacy, and tech entrepreneurship in Indigenous communities.',
    agency: 'Innovation, Science and Economic Development Canada',
    program: 'Connecting Families Initiative',
    category: 'Economic Development',
    eligibility: 'Indigenous organizations and tech entrepreneurs',
    applicationLink: 'https://www.ic.gc.ca/indigenous-tech',
    deadline: '2025-06-15',
    amount: '350000',
    currency: 'CAD',
    status: 'active',
    sourceUrl: 'https://www.ic.gc.ca',
  },
];

// Mock user applications data
export const mockApplications = [
  {
    id: 'app-1',
    grantId: '1',
    grantTitle: 'Indigenous Clean Energy Initiative',
    agency: 'Natural Resources Canada',
    applicationStatus: 'submitted',
    applicationDate: '2024-12-15',
    submissionDate: '2025-01-10',
    amountRequested: '500000',
    notes: 'Submitted proposal for solar panel installation in community center',
    deadline: '2025-03-31',
  },
  {
    id: 'app-2',
    grantId: '2',
    grantTitle: 'Indigenous Language Revitalization Grant',
    agency: 'Canadian Heritage',
    applicationStatus: 'approved',
    applicationDate: '2024-11-20',
    submissionDate: '2024-12-05',
    responseDate: '2025-01-15',
    amountRequested: '150000',
    amountApproved: '150000',
    notes: 'Approved for language education program. First installment received.',
    deadline: '2025-05-15',
  },
  {
    id: 'app-3',
    grantId: '5',
    grantTitle: 'Youth Education and Skills Development',
    agency: 'Employment and Social Development Canada',
    applicationStatus: 'in_progress',
    applicationDate: '2025-01-05',
    amountRequested: '200000',
    notes: 'Currently gathering required documentation and community support letters',
    deadline: '2025-04-30',
  },
  {
    id: 'app-4',
    grantId: '9',
    grantTitle: 'Housing and Shelter Development',
    agency: 'Canada Mortgage and Housing Corporation',
    applicationStatus: 'planning',
    applicationDate: '2025-01-18',
    amountRequested: '1200000',
    notes: 'Initial planning phase for 15-unit housing development',
    deadline: '2025-10-31',
  },
  {
    id: 'app-5',
    grantId: '7',
    grantTitle: 'Indigenous Health and Wellness Initiative',
    agency: 'Health Canada',
    applicationStatus: 'under_review',
    applicationDate: '2024-12-01',
    submissionDate: '2024-12-20',
    amountRequested: '300000',
    notes: 'Application under review by evaluation committee',
    deadline: '2025-09-30',
  },
];

// Mock metrics data
export const mockMetrics = {
  overview: {
    totalApplications: 5,
    approved: 1,
    pending: 3,
    rejected: 0,
    totalRequested: 2350000,
    totalApproved: 150000,
    successRate: 20,
  },
  byStatus: [
    { status: 'Approved', count: 1, percentage: 20, color: 'bg-green-500' },
    { status: 'Under Review', count: 1, percentage: 20, color: 'bg-yellow-500' },
    { status: 'Submitted', count: 1, percentage: 20, color: 'bg-blue-500' },
    { status: 'In Progress', count: 1, percentage: 20, color: 'bg-purple-500' },
    { status: 'Planning', count: 1, percentage: 20, color: 'bg-gray-500' },
  ],
  byCategory: [
    { category: 'Environment & Energy', applications: 1, approved: 0, amountRequested: 500000 },
    { category: 'Culture & Education', applications: 1, approved: 1, amountRequested: 150000 },
    { category: 'Education & Employment', applications: 1, approved: 0, amountRequested: 200000 },
    { category: 'Housing', applications: 1, approved: 0, amountRequested: 1200000 },
    { category: 'Health & Wellness', applications: 1, approved: 0, amountRequested: 300000 },
  ],
  timeline: [
    { month: 'Nov 2024', applications: 1, approvals: 0 },
    { month: 'Dec 2024', applications: 2, approvals: 0 },
    { month: 'Jan 2025', applications: 2, approvals: 1 },
  ],
};
